apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fboj06uhl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fboj06uhl-nodejs 
  name: fboj06uhl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fboj06uhl-nodejs 
